# Generated by Django 2.2.7 on 2019-11-19 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Midwife',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Marie Musterhebamme', max_length=30)),
                ('served_postcode_1', models.CharField(default='71334', max_length=5)),
                ('served_postcode_2', models.CharField(default='71332', max_length=5)),
                ('served_postcode_3', models.CharField(default='71336', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='MWRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postcode', models.CharField(default='71334', max_length=5)),
                ('birth_date', models.DateField()),
            ],
        ),
    ]
